services:
  db:
    image: postgres:15
    container_name: cmgs_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cmgs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # i dati persistono tra restart
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d cmgs"]
      interval: 5s
      timeout: 3s
      retries: 5


  redis:
    image: redis:7
    container_name: cmgs_redis
    ports:
      - "6379:6379"

  celery_worker:
    build: . # Usa lo stesso Dockerfile della tua app Python
    command: celery -A infra.celery.app worker --loglevel=info
    volumes:
      - .:/code # Se mappi il codice in locale per i cambi a caldo
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cmgs
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      celery_worker:
        condition: service_started


volumes:
  postgres_data: