# Generated by Django 5.2.12 on 2026-07-02 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialModelORM',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'financial_models',
                'indexes': [models.Index(fields=['is_active'], name='financial_m_is_acti_f7645f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelVersionORM',
            fields=[
                ('version_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50)),
                ('code_version', models.CharField(max_length=50, unique=True)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_id', models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='django.financialmodelorm')),
            ],
            options={
                'db_table': 'model_versions',
            },
        ),
        migrations.CreateModel(
            name='OutboxEventORM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outbox_events',
                'indexes': [models.Index(fields=['processed', 'created_at'], name='outbox_even_process_88222f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParameterVersionORM',
            fields=[
                ('parameter_version_id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_version', models.CharField(max_length=50)),
                ('parameter_set', models.JSONField(default=dict)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_id', models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.PROTECT, related_name='parameter_sets', to='django.financialmodelorm')),
            ],
            options={
                'db_table': 'model_parameters',
            },
        ),
        migrations.CreateModel(
            name='ModelRunORM',
            fields=[
                ('run_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('outputs_generated', 'outputs_generated'), ('completed', 'completed'), ('checks_failed', 'checks_failed'), ('checks_error', 'checks_error'), ('failed', 'failed')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('outputs', models.JSONField(blank=True, null=True)),
                ('check_results', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('model_id', models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='django.financialmodelorm')),
                ('model_version_id', models.ForeignKey(db_column='model_version_id', on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='django.modelversionorm')),
                ('parameter_version_id', models.ForeignKey(db_column='parameter_version_id', on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='django.parameterversionorm')),
            ],
            options={
                'db_table': 'model_runs',
            },
        ),
        migrations.CreateModel(
            name='AnyLogORM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('model_registered', 'model_registered'), ('model_activated', 'model_activated'), ('model_deactivated', 'model_deactivated'), ('model_version_registered', 'model_version_registered'), ('model_version_approved', 'model_version_approved'), ('model_version_rejected', 'model_version_rejected'), ('model_version_deprecated', 'model_version_deprecated'), ('parameters_registered', 'parameters_registered'), ('parameters_approved', 'parameters_approved'), ('parameters_rejected', 'parameters_rejected'), ('parameters_deprecated', 'parameters_deprecated'), ('run_started', 'run_started'), ('run_outputs_generated', 'run_outputs_generated'), ('run_failed', 'run_failed'), ('checks_started', 'checks_started'), ('checks_completed', 'checks_completed'), ('checks_failed', 'checks_failed'), ('checks_not_executed', 'checks_not_executed'), ('action_executed', 'action_executed'), ('system_error', 'system_error'), ('system_warning', 'system_warning')], max_length=50)),
                ('author', models.CharField(default='SYSTEM', max_length=150)),
                ('details', models.JSONField(default=dict)),
                ('relevance', models.CharField(choices=[('major', 'major'), ('minor', 'minor')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model_id', models.ForeignKey(blank=True, db_column='model_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='django.financialmodelorm')),
                ('run_id', models.ForeignKey(blank=True, db_column='run_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='django.modelrunorm')),
            ],
            options={
                'db_table': 'audit_anylog',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['run_id', 'timestamp'], name='audit_anylo_run_id_1b2f1c_idx'), models.Index(fields=['model_id', 'timestamp'], name='audit_anylo_model_i_b56a82_idx'), models.Index(fields=['relevance', 'timestamp'], name='audit_anylo_relevan_fe1f59_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='modelversionorm',
            index=models.Index(fields=['approved'], name='model_versi_approve_73e39b_idx'),
        ),
        migrations.AddConstraint(
            model_name='modelversionorm',
            constraint=models.UniqueConstraint(fields=('model_id', 'version'), name='unique_model_version'),
        ),
        migrations.AddIndex(
            model_name='parameterversionorm',
            index=models.Index(fields=['approved'], name='model_param_approve_ad910f_idx'),
        ),
        migrations.AddConstraint(
            model_name='parameterversionorm',
            constraint=models.UniqueConstraint(fields=('model_id', 'parameter_version'), name='unique_parameter_version'),
        ),
        migrations.AddIndex(
            model_name='modelrunorm',
            index=models.Index(fields=['model_id', 'status', 'created_at'], name='model_runs_model_i_7fd4eb_idx'),
        ),
        migrations.AddIndex(
            model_name='modelrunorm',
            index=models.Index(fields=['model_id', 'model_version_id', 'parameter_version_id'], name='model_runs_model_i_42f6ce_idx'),
        ),
        migrations.AddIndex(
            model_name='modelrunorm',
            index=models.Index(fields=['status', 'created_at'], name='model_runs_status_0548af_idx'),
        ),
    ]
