# Generated by Django 5.2.12 on 2026-07-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anylogorm',
            old_name='model_id',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='anylogorm',
            old_name='run_id',
            new_name='run',
        ),
        migrations.RenameField(
            model_name='modelrunorm',
            old_name='model_id',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='modelrunorm',
            old_name='model_version_id',
            new_name='model_version',
        ),
        migrations.RenameField(
            model_name='modelrunorm',
            old_name='parameter_version_id',
            new_name='parameter_version',
        ),
        migrations.RenameField(
            model_name='modelversionorm',
            old_name='model_id',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='parameterversionorm',
            old_name='model_id',
            new_name='model',
        ),
        migrations.AddConstraint(
            model_name='parameterversionorm',
            constraint=models.CheckConstraint(condition=models.Q(('approved', False), ('parameter_version_id__isnull', False), _connector='OR'), name='prevent_insert_as_approved'),
        ),
    ]
