# Generated by Django 5.2.12 on 2026-07-06 18:17

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmg_infra', '0002_rename_model_id_anylogorm_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anylogorm',
            name='details',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='modelrunorm',
            name='check_results',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='modelrunorm',
            name='outputs',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='outboxeventorm',
            name='payload',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='parameterversionorm',
            name='parameter_set',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
